import pygame

#GAME SIZE
COLUMS = 10
ROWS = 20
CELL_SIZE = 40
GAME_WIDTH, GAME_HEIGHT = COLUMS * CELL_SIZE, ROWS * CELL_SIZE

#SIDE BAR SIZE
SIDEBAR_WIDTH = 200
PREVIEW_HEIGHT_FRACTION = 0.7
SCORE_HEIGHT_FRACTION = 1 - PREVIEW_HEIGHT_FRACTION

#WINDOW SIZE
PADDING = 20
WINDOW_WIDTH = GAME_WIDTH + SIDEBAR_WIDTH + PADDING * 3
WINDOW_HEIGHT = GAME_HEIGHT + SIDEBAR_WIDTH * 2

#COLORS
GRAY = '#1C1C1C'